# Generated by Django 5.1.6 on 2025-03-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_recipeimage_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='descsription',
            new_name='description',
        ),
    ]
